### ISSUE TITLE
Running diepvries with multiple sources

### ISSUE THREAD

**Issue by P-mir** [PicnicSupermarket/diepvries#36]
Hi, it's an interesting project, thank you for sharing :)

Going through the documentation, I see only examples using one extract table and one source at a time, what is the intended use for multiple sources ? For instance a satellite containing data coming from multiple tables from different sources.

**Comment by matthieucan** [comment]
Hi @P-mir ,thanks for your interest! The intended use for multiple sources would be issuing multiple `DataVaultLoad` objects, linked to different sources and pointing to the same target. This way, it allows having different pipelines, schedules, etc. Does that make sense?

**Comment by P-mir** [comment]
How would then be handled the generation of a query for a link between two hubs containing data from different sources ? It seems to require a simultaneous load of two sources.

**Comment by dlouseiro** [comment]
> How would then be handled the generation of a query for a link between two hubs containing data from different sources ? It seems to require a simultaneous load of two sources.

Hey @P-mir , thanks for your interest in the project.

I can share a bit our guidelines on modelling and processing using `diepvries`.

From a modelling perspective, our guideline is:
- Satellites are populated by only one source. If we receive details for a given entity (hub satellite) or details of the relationship between 2+ entities (link satellite) from multiple sources we create multiple satellites.
- Links and hubs (backbone of the model) can be populated by multiple sources.

In terms of staging/extraction tables, we usually have one extraction table per source + level of granularity. So imagining a scenario where we have a source endpoint that gives us one row per order placed by customers. Although, one of the columns received from this endpoint is the order lines (an array containing all products ordered by that customer in that same order). In this scenario we have one source, but two levels of granularity (order level and order/product level). In this case we'd create two `DataVaultLoad` instances and two extraction/staging tables:
- The first one, let's call it `extract_orders` would have data at the order level (one row per order) and would populate order level tables: e.g., `h_order`, `l_order_customer` and `hs_order`.
- The second one, let's call it `extract_order_lines` would have data at the order/product level (one row per order/product after flattening of the `order lines` array) and would populate tables a the `order/product` level: e.g. `h_order`, `h_product`, `l_order_product` and `ls_order_product`.
- Each `DataVaultLoad` instance would fetch data from different extraction tables and populate different tables, the only common table being `h_order`.
- So, in summary, one single extraction process, one single call to the source endpoint, but multiple extraction tables. 

> For instance a satellite containing data coming from multiple tables from different sources.

The scenario to which you're referring above is something that we try to avoid, both from a modelling and data processing perspective, but it is possible to handle. Let's imagine your use case is: you have two sources that provide you customer data and you want to combine the data from both sources in the same satellite. Your `DataVaultLoad` instance would populate two tables: `h_customer` and `hs_customer`. You could do something like:
1. Extract data from both sources, storing the data of each source in its own table;
2. Combine both sources using SQL and create an extraction table that has all fields needed to populate `h_customer` and `hs_customer`, combining the data from both sources.
3. Instantiate a `DataVaultLoad` passing `h_customer` and `hs_customer` as target tables and the extraction table from point 2 as extract table.

In our setup, we'd probably avoid having `hs_customer` being populated by two sources, but have two satellites instead: `hs_customer_<source 1>` with the customer details provided by source 1 and `hs_customer_<source 2>` with the customer details provided by source 2.

> How would then be handled the generation of a query for a link between two hubs containing data from different sources ? It seems to require a simultaneous load of two sources.

In this case, we'd have two completely different extraction processes, different `DataVaultLoad` instances, populating the same link/hubs, running either concurrently or in serial. We'd simply avoid having the same satellite being populated by the same source, as mentioned above.

Some extra notes:
- `diepvries`' purpose is to generate SQL to load a Data Vault model, given one staging table. It is completely agnostic to the way you extract data, design or schedule your extraction processes. Essentially, everything that happens until the generation of the extraction table is external to `diepvries` and is up to the development team to define guidelines on what works best. The best I can do is to share a bit of our guidelines as I'm doing here, but these are not "`diepvies`' concerns" per se, as in are not within `diepvries`' scope.
- The code generated by `diepvries` focuses on having atomic/transaction-safe commands, allowing one to safely run processes in parallel without having unintended side-effects, hence the usage of `MERGE` commands everywhere, even when not specifically needed (we had issues with Snowflake `INSERT`s in the past, for example, as they're not truly atomic/idempotent). I can tell you that in our own implementation, we have multiple processes running concurrently and populating the same hubs/links without any major side effect.


Hope this helps!

**Comment by P-mir** [comment]
Hello @dlouseiro, we are building a data vault on databricks and this helps a lot to clarify things for me and to understand what needs and what does not need to be adapted. Thank you for both of your answers !

**Comment by matthieucan** [comment]
Best of luck for your project! Beware that `diepvries` only supports Snowflake at the moment :)
